# -*- coding: utf-8 -*-
"""emotionD_AIchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WI6Ha7vjDToTrsBJa-ueuxVfshak_JSG
"""

# Step 1: Install and import required libraries for emotion model

# Install required packages (run in Colab)
!pip install datasets transformers torch scikit-learn pandas

# Import libraries
import torch  # for deep learning model
import pandas as pd  # for data handling
from datasets import load_dataset  # to load GoEmotions dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification  # BERT model tools
from sklearn.model_selection import train_test_split  # splitting data

# Load dataset from HuggingFace
dataset = load_dataset("go_emotions")

# Print dataset structure (train/validation/test)
print(dataset)

# Convert train split to DataFrame
df = dataset["train"].to_pandas()

# Keep only needed columns (text + labels)
df = df[["text", "labels"]]

# Remove empty rows (if any)
df = df.dropna()

# Reset index after cleaning
df = df.reset_index(drop=True)

# Show sample data
print(df.head())

import numpy as np

# Get number of emotion classes
num_labels = dataset["train"].features["labels"].feature.num_classes

# Function to convert label list → multi-hot vector
def multi_hot(labels):
    vec = np.zeros(num_labels)  # create empty vector
    vec[labels] = 1             # set 1 for present emotions
    return vec

# Apply conversion to dataset
df["multi_hot"] = df["labels"].apply(multi_hot)

# Show result
print(df[["text", "labels", "multi_hot"]].head())

# Step 5 (updated): Split dataset into 75/25 ratio

from sklearn.model_selection import train_test_split

# 75% training, 25% testing split
train_df, test_df = train_test_split(df, test_size=0.25, random_state=42)

# Show sizes
print("Train size:", len(train_df))
print("Test size:", len(test_df))

# Step 6: Load pretrained DistilBERT model and tokenizer for multi-label emotion classification

from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Load tokenizer (converts text → tokens)
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# Load pretrained DistilBERT model (we will fine-tune it later)
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels,   # number of emotion classes
    problem_type="multi_label_classification"
)

print("Model and tokenizer loaded successfully")

# Step 7: Modify DistilBERT model for multi-label classification

from transformers import AutoModelForSequenceClassification

# Load model with correct setup for multi-label task
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels,   # number of emotion classes
    problem_type="multi_label_classification"  # enables sigmoid + BCE loss
)

# Set activation expectation (handled internally, but good to know)
print("Model modified for multi-label classification")

# Step 8: Tokenize dataset for DistilBERT training

import torch

# Function to tokenize text + attach labels
def tokenize_data(texts, labels):
    encodings = tokenizer(
        list(texts),
        truncation=True,
        padding=True,
        max_length=128,
        return_tensors="pt"
    )

    encodings["labels"] = torch.tensor(list(labels), dtype=torch.float)
    return encodings

# Tokenize train and test sets
train_encodings = tokenize_data(train_df["text"], train_df["multi_hot"])
test_encodings = tokenize_data(test_df["text"], test_df["multi_hot"])

print("Tokenization complete")

# Step 9: Training setup for DistilBERT multi-label emotion model

from torch.utils.data import Dataset, DataLoader

# Custom dataset class
class EmotionDataset(Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __len__(self):
        return len(self.encodings["input_ids"])

    def __getitem__(self, idx):
        return {key: val[idx] for key, val in self.encodings.items()}

# Create dataset objects
train_dataset = EmotionDataset(train_encodings)
test_dataset = EmotionDataset(test_encodings)

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

print("Training setup complete (datasets + dataloaders ready)")

print(len(train_loader))

# Step 10: Simple working training loop

import torch
from torch.optim import AdamW

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = AdamW(model.parameters(), lr=2e-5)
epochs = 3

print("Training started")

for epoch in range(epochs):
    print("Epoch", epoch+1)

    total_loss = 0
    model.train()

    for batch in train_loader:

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print("Loss:", total_loss / len(train_loader))

print("Training finished")

epochs = 2

for epoch in range(epochs):
    print("Epoch", epoch+1)
    total_loss = 0
    model.train()

    for batch in train_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print("Loss:", total_loss / len(train_loader))

print("Training finished")

#=================================================================================================================

#=================================================================================================================

#=================================================================================================================

!pip install transformers accelerate gtts

from transformers import pipeline

# Load Emotion Detector
emotion_detector = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base"
)

# Load TinyLlama
llm = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    torch_dtype="auto",
    device_map="auto"
)

print("✅ Models loaded!")

from gtts import gTTS
import IPython.display as ipd

# Emotion Detection Function
def detect_emotion(text):
    result = emotion_detector(text)[0]
    return result['label']

# TinyLlama Response Function
def generate_response(user_input, emotion):
    prompt = f"""<|system|>
You are an empathetic assistant. The user is feeling {emotion}. Respond kindly in 2-3 sentences.
</s>
<|user|>
{user_input}
</s>
<|assistant|>"""

    output = llm(prompt, max_new_tokens=150, do_sample=True, temperature=0.7)
    response = output[0]['generated_text'].split("<|assistant|>")[-1].strip()
    return response

# Voice Output Function
def speak(text):
    tts = gTTS(text=text, lang='en')
    tts.save("response.mp3")
    ipd.display(ipd.Audio("response.mp3", autoplay=True))

print("✅ Functions ready!")

def run(user_input):
    emotion = detect_emotion(user_input)
    print(f"🎭 Detected Emotion: {emotion}")

    reply = generate_response(user_input, emotion)
    print(f"🤖 Bot: {reply}")

    speak(reply)

run(input("YOU:"))

run(input("YOU:"))

run(input("YOU:"))



#=============================================================================================================================

#=============================================================================================================================

#==============================================================================================================================

from google.colab import drive
drive.mount('/content/drive')

import os
os.makedirs("/content/drive/MyDrive/emotionD_aiBot/emotion_model", exist_ok=True)

model.save_pretrained("/content/drive/MyDrive/emotionD_aiBot/emotion_model")
tokenizer.save_pretrained("/content/drive/MyDrive/emotionD_aiBot/emotion_model")

print("✅ Saved to Google Drive as 'emotionD_aiBot'!")

from google.colab import drive
drive.mount('/content/drive')

from transformers import pipeline

emotion_detector = pipeline(
    "text-classification",
    model="/content/drive/MyDrive/emotionD_aiBot/emotion_model"
)

llm = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    torch_dtype="auto",
    device_map="auto"
)

print("✅ emotionD_aiBot Ready!")

!pip install gtts
from gtts import gTTS
import IPython.display as ipd

# Emotion Detection Function
def detect_emotion(text):
    result = emotion_detector(text)[0]
    return result['label']

# TinyLlama Response Function
def generate_response(user_input, emotion):
    prompt = f"""<|system|>
You are an empathetic assistant. The user is feeling {emotion}. Respond kindly in 2-3 sentences.
</s>
<|user|>
{user_input}
</s>
<|assistant|>"""

    output = llm(prompt, max_new_tokens=150, do_sample=True, temperature=0.7)
    response = output[0]['generated_text'].split("<|assistant|>")[-1].strip()
    return response

# Voice Output Function
def speak(text):
    tts = gTTS(text=text, lang='en')
    tts.save("response.mp3")
    ipd.display(ipd.Audio("response.mp3", autoplay=True))

print("✅ Functions ready!")

def run(user_input):
    emotion = detect_emotion(user_input)
    print(f"🎭 Detected Emotion: {emotion}")

    reply = generate_response(user_input, emotion)
    print(f"🤖 Bot: {reply}")

    speak(reply)





